ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

_sap:
  cluster_name: jack-kr-sap
  major_version: "18"
  minor_version: "2"
  build_version: "1"
  patch_version: ""
  download_url: ""
  download: false
  base_path: /root
  admin_user: admin
  admin_passwd: changeme
  bin_type: tar
  net:
    conn: "udp"                     # dpdk or udp
    gateway: "192.168.2.1"
    ha1: 1
    ha2: 2
    type: "virtual"                 # or physical
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  client:
    net:
      type: "virtual"               # or physical
      cores: 1
      ipaddr0: "192.168.0.19"
      ipaddr1: "192.168.1.19"
      ipaddr2: "192.168.2.19"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02" ]
  debug_opt: ""  # --debug

