---
# https://docs.us.sios.com/spslinux/9.5.1/en/topic/install-sap-hana-and-configure-system-replication
- name: Verify that the HDB00 Instance is Running Successfully
  shell: |
    su - hxeadm -c "sapcontrol -nr 90 -function GetProcessList"
  register: running_instance_verified
  ignore_errors: true
- debug: msg={{ running_instance_verified }}


# Execute the following commands on both sles15-ha01 and sles15-ha02 to create backups of the SYSTEMDB database and the HXE tenant database,
# replacing <SYSTEM User Password> with the password for the SYSTEM database user:
- name: Back up the SYSTEMDB and HXE Databases on Both Nodes
  shell: |
    su - hxeadm -c "hdbsql -i 90 -u SYSTEM -p Changeme12 -d SystemDB \"BACKUP DATA USING FILE ('/hana/shared/HXE/HDB00')\""
    su - hxeadm -c "hdbsql -i 90 -u SYSTEM -p Changeme12 -d HXE \"BACKUP DATA USING FILE ('/hana/shared/HXE/HDB90')\""
  register: system_db_backup
  ignore_errors: true
  when: inventory_hostname in groups['master']
- debug: msg={{ system_db_backup }}
  when: print_debug == true and inventory_hostname in groups['master']


- name: Enable System Replication using Site Name
  shell: |
    su - hxeadm -c "hdbnsutil -sr_enable --name=ha-site01"
  register: system_replica_enabled
  ignore_errors: true
  when: inventory_hostname in groups['master']
- debug: msg={{ system_replica_enabled }}
  when: print_debug == true and inventory_hostname in groups['master']


- name: Copy Security Key files from Master to Slave
  shell: |
    scp -r /usr/sap/HXE/SYS/global/security/rsecssfs/ root@sles15-ha02:/usr/sap/HXE/SYS/global/security/
  register: security_key_copied
  ignore_errors: true
  when: inventory_hostname in groups['master']
- debug: msg={{ security_key_copied }}
  when: print_debug == true and inventory_hostname in groups['master']


- name: Stop the HDB00 instance on Slave
  shell: |
    su - hxeadm -c "sapcontrol -nr 90 -function StopSystem HDB"
  register: instance_stopped
  ignore_errors: true
  when: inventory_hostname in groups['slave']
- debug: msg={{ instance_stopped }}
  when: print_debug == true and inventory_hostname in groups['slave']


- name: Register sles15-node02 as a Secondary System Replication Site using Site Name
  shell: |
    su - hxeadm -c "hdbnsutil -sr_register --remoteHost=sles15-ha01 --remoteInstance=90 --replicationMode=sync --operationMode=logreplay --name=ha-site02"
  register: secondary_registered
  ignore_errors: true
  when: inventory_hostname in groups['slave']
- debug: msg={{ secondary_registered }}
  when: print_debug == true and inventory_hostname in groups['slave']


- name: Start the HDB00 instance on Slave
  shell: |
    su - hxeadm -c "sapcontrol -nr 90 -function StartSystem HDB"
  register: instance_started
  ignore_errors: true
  when: inventory_hostname in groups['slave']
- debug: msg={{ instance_started }}
  when: print_debug == true and inventory_hostname in groups['slave']


- name: The Replication and Operation Modes are Primary/Primary and Sync/Logreplay on Master and Slave Respectively
  shell: |
    su - hxeadm -c "hdbnsutil -sr_state"
  register: system_replica_state
  ignore_errors: true
  when: inventory_hostname in groups['master']
- debug: msg={{ system_replica_state }}
  when: print_debug == true and inventory_hostname in groups['master']


- name: Verify that the HDB00 Instance is Running Successfully
  shell: |
    su - hxeadm -c "sapcontrol -nr 90 -function GetProcessList"
  register: running_instance_verified
  ignore_errors: true
- debug: msg={{ running_instance_verified }}

