---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'openSUSE Leap'


- name: Set facts for Installing SAP Hana Express
  import_tasks: set-hxe-facts.yml
  tags: install, uninstall


#- name: Upload SAP HANA Express Binary
#  import_tasks: upload-hxe-bin.yml
#  tags: upload


- name: Deploy SAP HANA Express
  import_tasks: deploy-hxe.yml
  tags: install
  when: deploy_hxe


- name: Enable System Replicaton
  import_tasks: enable-replica.yml
  tags: install
  when: enable_replica


- name: Dsiable System Replicaton
  import_tasks: disable-replica.yml
  tags: uninstall
  when: disable_replica


#- name: Remove SAP HANA Express Binary
#  import_tasks: removep-hxe-bin.yml
#  tags: uninstall


- name: Destroy SAP HANA Express
  import_tasks: destroy-hxe.yml
  tags: uninstall
  when: destroy_hxe

